# Generated by Django 5.2.5 on 2025-09-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('vinculo', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('CLT', 'CLT'), ('HORISTA', 'Horista'), ('DIARISTA', 'Diarista')], max_length=10)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('especialidades', models.ManyToManyField(related_name='profissionais', to='profissionais.especialidade')),
                ('planos_saude', models.ManyToManyField(blank=True, related_name='profissionais', to='profissionais.planosaude')),
            ],
        ),
    ]
