# Generated by Django 5.2.5 on 2025-09-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planosaude',
            old_name='nome',
            new_name='plano',
        ),
    ]
