# Generated by Django 5.2.5 on 2025-09-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_rename_nome_planosaude_plano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planosaude',
            old_name='plano',
            new_name='nome',
        ),
    ]
