# Generated by Django 5.2.5 on 2025-09-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('profissionais', '0002_rename_nome_planosaude_plano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='nome_plano_saude',
        ),
        migrations.AddField(
            model_name='paciente',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profissionais.planosaude'),
        ),
    ]
