# Generated by Django 5.2.5 on 2025-09-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('profissionais', '0003_rename_plano_planosaude_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.especialidade'),
        ),
    ]
