# Generated by Django 5.2.5 on 2025-09-05 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_consulta_especialidade'),
        ('profissionais', '0003_rename_plano_planosaude_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='nome_convenio',
        ),
        migrations.AddField(
            model_name='consulta',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profissionais.planosaude'),
        ),
    ]
